# to be used with vhs https://github.com/charmbracelet/vhs
Output demo.mp4

Set FontSize 22
Set Width 1300
Set Height 650
Set Theme "Dark Pastel"
Set WindowBar Colorful
Set Padding 10
Set TypingSpeed 50ms

Type "songs-history.exe"
Sleep 500ms
Enter
Sleep 1s

Type "songs-history.exe --help"
Sleep 500ms
Enter
Sleep 1s

Type "songs-history.exe ..\songs-backup\"
Sleep 500ms
Enter
Sleep 1s

Type "songs-history.exe ..\songs-backup\ -f"
Sleep 500ms
Enter
Sleep 2s
